apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    instance: app
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/node
              labelSelector:
                matchLabels:
                  instance: app
      containers:
        - name: nginx
          image: ghcr.io/tarch64/eks-todo-app-nginx:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
