apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-todo-app-deployment
  namespace: eks-todo-app
  labels:
    app: eks-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-todo-app
  template:
    metadata:
      labels:
        app: eks-todo-app
      spec:
        containers:
        - name: app
          image: ghcr.io/tarch64/eks-todo-app-nginx:latest
          ports:
          - containerPort: 80

        - name: app
          image: ghcr.io/tarch64/eks-todo-app-backend:latest
          ports:
            - containerPort: 3000