apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    instance: app
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/node
              labelSelector:
                matchLabels:
                  instance: app
      containers:
        - name: backend
          image: ghcr.io/tarch64/eks-todo-app-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://admin:admin@mongo:27017/admin
          imagePullPolicy: Always
